name: Actions workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: |
          pwd
          ls
      - name: simple javascript action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Sabari
      - name: log greeting time
        run: echo "${{ steps.greet.outputs.time }}"
      - name: log greeting time out
        run: echo "${{ steps.greet.outputs }}"